/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#343029",
        "inverse-primary": "#b8ccb6",
        "surface": "#fff8f3",
        "surface-container-highest": "#eae1d7",
        "on-secondary-fixed-variant": "#79301a",
        "outline-variant": "#c3c8c0",
        "on-error": "#ffffff",
        "background": "#fff8f3",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "tertiary": "#332400",
        "surface-container-low": "#fcf2e8",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "secondary-container": "#ff987b",
        "surface-container": "#f6ece2",
        "on-tertiary-container": "#c7a14b",
        "surface-variant": "#eae1d7",
        "surface-bright": "#fff8f3",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#5b4300",
        "tertiary-fixed-dim": "#eac168",
        "on-secondary-container": "#772e19",
        "on-surface": "#1f1b15",
        "on-background": "#1f1b15",
        "on-primary-fixed-variant": "#3a4b3a",
        "secondary": "#97462f",
        "primary-container": "#2f4030",
        "primary-fixed": "#d4e8d1",
        "on-primary-container": "#98ab97",
        "secondary-fixed": "#ffdbd1",
        "on-error-container": "#93000a",
        "surface-container-high": "#f0e7dd",
        "primary-fixed-dim": "#b8ccb6",
        "on-primary-fixed": "#0f1f11",
        "secondary-fixed-dim": "#ffb5a0",
        "tertiary-container": "#4d3800",
        "outline": "#747872",
        "inverse-on-surface": "#f9efe5",
        "surface-dim": "#e2d9cf",
        "on-tertiary-fixed": "#261a00",
        "tertiary-fixed": "#ffdf9e",
        "primary": "#1a2a1b",
        "on-surface-variant": "#434842",
        "on-secondary-fixed": "#3b0900",
        "surface-tint": "#516351"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "sm": "0.125rem",
        "md": "0.25rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "9999px"
      },
      spacing: {
        "gutter-desktop": "1.5rem",
        "space-2xl": "3rem",
        "margin-desktop": "2rem",
        "space-xs": "0.5rem",
        "gutter-mobile": "0.75rem",
        "margin-mobile": "1rem",
        "space-md": "1rem",
        "space-3xl": "4rem",
        "space-sm": "0.75rem",
        "space-xl": "2rem",
        "space-2xs": "0.25rem",
        "space-lg": "1.5rem",
        "space-3xs": "0.125rem"
      },
      fontFamily: {
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "data-xl": ["IBM Plex Sans", "sans-serif"],
        "data-lg": ["IBM Plex Sans", "sans-serif"],
        "data-md": ["IBM Plex Sans", "sans-serif"],
        "label-md": ["IBM Plex Sans", "sans-serif"],
        "body-sm": ["IBM Plex Sans", "sans-serif"],
        "label-lg": ["IBM Plex Sans", "sans-serif"],
        "headline-xl": ["Playfair Display", "serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "label-sm": ["IBM Plex Sans", "sans-serif"],
        "body-md": ["IBM Plex Sans", "sans-serif"],
        "body-lg": ["IBM Plex Sans", "sans-serif"],
        "headline-md": ["Playfair Display", "serif"],
        "headline-xl-mobile": ["Playfair Display", "serif"],
        "headline-sm": ["Playfair Display", "serif"]
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "data-xl": ["48px", { "lineHeight": "52px", "fontWeight": "700" }],
        "data-lg": ["28px", { "lineHeight": "32px", "fontWeight": "600" }],
        "data-md": ["18px", { "lineHeight": "24px", "fontWeight": "600" }],
        "label-md": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "body-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "label-lg": ["14px", { "lineHeight": "20px", "fontWeight": "600" }],
        "headline-xl": ["44px", { "lineHeight": "52px", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "600" }],
        "label-sm": ["10px", { "lineHeight": "12px", "fontWeight": "600" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-xl-mobile": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
        "headline-sm": ["18px", { "lineHeight": "26px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
